apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: microservice-sa
    namespace: default
roleRef:
  kind: Role
  name: microservice-role
  apiGroup: rbac.authorization.k8s.io
