apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microservice-role-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: microservice-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: microservice-role
  apiGroup: rbac.authorization.k8s.io
