apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microservice-role
  namespace: dev
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
      - configmaps
    verbs:
      - get
      - list
      - watch
