apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
  namespace: dev
data:
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
  application.yaml: |-
    config:
      text: Configurando ambientes!
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      text: Configurando para ambiente dev
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      text: Configurando para ambiente prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
  namespace: dev
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
