apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: dev
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: postgres-disk
    fsType: ext4
